import { IDependencyFromNodeModuleWithoutDependencies } from './IDependencyFromNodeModuleWithoutDependencies';
export declare class DependencyFromNodeModuleWithoutDependencies implements IDependencyFromNodeModuleWithoutDependencies {
}
