export const restrictedClassMemberNames = new Set([
    'contextName',
    'notInitializedConfigMarker',
    'beanConfigurationRecord',
    'lifecycleConfiguration',
    '___postConstruct',
    '___beforeDestruct',
    'singletonMap',
    '_config',
    'config',
    'getBean',
    'getPrivateBean',
    'getBeanConfiguration',
    'getBeans',
]);
