name: dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install DI Cat Dependencies
        run: yarn

      - name: Build and test DI-Cat
        run: yarn run build-and-test

      - name: publish to npm
        run: cd dist && npm version 0.0.${{ github.run_number }}-beta && npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
